GET http://localhost:3000/clients

###

GET http://localhost:3000/clients/123

###

POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
  "name": "test client",
  "birthDate": "2000-01-01",
  "sex": "ssssss"
}

###

POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
  "name": "test client",
  "birthDate": "2000-01-01",
  "sex": "male"
}

###

POST http://localhost:3000/clients/problem/6da5d999-6692-4f58-b6d8-9ac805f5e873 HTTP/1.1
Content-Type: application/json

{
  "problems": ["019e3ec9-1004-7000-8682-360390c157d2", "019e3ec9-1004-7003-a888-48ca8c8bea88"]
}

###

GET http://localhost:3000/clients/risk